//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Electric : Engine
{
	public virtual float GetBatteryTimeLeft()
	{
		throw new System.NotImplementedException();
	}

	public virtual float GetMaxBatteryTime()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RechargeBattery(float i_HoursToAdd)
	{
		throw new System.NotImplementedException();
	}

}

