//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Engine
{
	private float m_CurrenttEnergyAmount
	{
		get;
		set;
	}

	private float m_MaxEnergyAmount
	{
		get;
		set;
	}

}

