//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FuelEngine : Engine
{
	private eFuelType m_FuelType
	{
		get;
		set;
	}

	public virtual eFuelType GetFuelType()
	{
		throw new System.NotImplementedException();
	}

	public virtual float GetCurrentFuelAmount()
	{
		throw new System.NotImplementedException();
	}

	public virtual float GetMaxFuelAmount()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Refuel(float i_FuelAmountToAdd, FuelType i_FuelType)
	{
		throw new System.NotImplementedException();
	}

}

