//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Garage
{
	public virtual void InsertCarForTreatment(string i_License)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetCarLicenseList(i_eVehicleTreatmentStatus i_Status)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeCarStatus(string i_License, eVehicleTreatmentStatus i_ NewStatus)
	{
		throw new System.NotImplementedException();
	}

	public virtual void InflateAirInWheelsToMax(string i_License)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Refuel(string i_License, eFuelType i_FuelType, float i_Amount)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Recharge(string i_License, float i_MinutesToCharge)
	{
		throw new System.NotImplementedException();
	}

	public virtual void PrintCarDetails(string i_License)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Start()
	{
		throw new System.NotImplementedException();
	}

	public virtual void PrintMenu()
	{
		throw new System.NotImplementedException();
	}

}

