//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class VehicleTreatment
{
	private string m_OwnerName
	{
		get;
		set;
	}

	private string m_OwnerPhoneNumber
	{
		get;
		set;
	}

	private eVehicleTreatmentStatus m_Status
	{
		get;
		set;
	}

	public VehicleTreatment()
	{
	}

}

