//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FuelEngine : Engine
{
    private eFuelType m_FuelType;

	public virtual eFuelType GetFuelType()
	{
        return m_FuelType;
	}

	public virtual float GetCurrentFuelAmount()
	{
        return m_CurrentEnergyAmount;
	}

	public virtual float GetMaxFuelAmount()
	{
        return m_MaxEnergyAmount;
	}

	public virtual void Refuel(float i_FuelAmountToAdd, eFuelType i_FuelType)
	{
		if (i_FuelType == m_FuelType)
        {
            m_CurrentEnergyAmount += i_FuelAmountToAdd;
            if(m_CurrentEnergyAmount > m_MaxEnergyAmount)
            {
                m_CurrentEnergyAmount = m_MaxEnergyAmount;
            }
        }
	}

}

