//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MotorCycle : Vehicle
{
	private eMotorCycleLicenseType m_LicenseType
	{
		get;
		set;
	}

	private int m_EngineCapacity
	{
		get;
		private set;
	}

}

