//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Truck : Vehicle
{
	private bool m_CarryDangerousChemicals
	{
		get;
		set;
	}

	private float m_MaxCarryWeightAllowed
	{
		get;
		private set;
	}

}

