//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Vehicle
{
	private string m_Model
	{
		get;
		set;
	}

	private string m_LicenseNumber
	{
		get;
		set;
	}

	private List<Wheel> m_Wheels
	{
		get;
		set;
	}

	private Engine m_Engine
	{
		get;
		set;
	}

	private float m_EnergyLeftPercentage
	{
		get;
		set;
	}

}

